server:
  port: 8080

spring:
  datasource:
    username: test
    password: test
    url: jdbc:mysql://49.234.27.45:3306/testDB?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.demo.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug